### ISSUE TITLE
Warning text

### ISSUE THREAD

**Issue by helena-moj** [ministryofjustice/mojdt-design-system-backlog#19]
From the HMPPS library: https://moj-pattern-library.herokuapp.com/#/components/warning-text

**Comment by helena-moj** [comment]
**Service:** Prison NOMIS
**Department:** HMPPS

<kbd>![screen shot 2018-12-12 at 11 07 26](https://user-images.githubusercontent.com/43538843/49865960-4969ef80-fdfe-11e8-8f08-1c81cd5e67c3.png)</kbd>

**Comment by whatterz** [comment]
Not doing as already in GOV.UK Design System
