### ISSUE TITLE
Date picker

### ISSUE THREAD

**Issue by helena-moj** [ministryofjustice/mojdt-design-system-backlog#21]
**Service:** Prison NOMIS
**Department:** HM Prison and Probation Service

<kbd>![date picker 2018-12-12 11_16_33](https://user-images.githubusercontent.com/43538843/49866729-7b7c5100-fe00-11e8-9290-414a4ea70f10.gif)</kbd>

**Comment by reyrrep** [comment]
Service: Moving People Safely
Department: HMPPS
![mps_datepicker](https://user-images.githubusercontent.com/24682124/51485508-313ea600-1d96-11e9-9fe1-3a735350d2d5.gif)

**Comment by adamsilver** [comment]
Added examples to the GOV.UK Design System backlog. Closing this.

https://github.com/alphagov/govuk-design-system-backlog/issues/17
