### ISSUE TITLE
Case list

### ISSUE THREAD

**Issue by helena-moj** [ministryofjustice/mojdt-design-system-backlog#8]
**Service:** Track a query
**Phase:** Beta
**Department:** Ministry of Justice

<kbd>![all open cases track a query 1](https://user-images.githubusercontent.com/43538843/49010205-66e65a80-f16a-11e8-8e34-1855b91a9e74.png)</kbd>

**Comment by whatterz** [comment]
**Service:** Claim for Crown court defence
**Phase:** Live
**Department:** Legal Aid Agency

**Claims list for advocates**
_The prototype version is shown and is missing the search form._
![laa_cccd_claims_list_advocates](https://user-images.githubusercontent.com/23444/49014543-6785ed80-f178-11e8-8c06-8a3dd7256a18.png)

**Claims list for litigators**
_The prototype version is shown and is missing the search form._
![laa_cccd_claims_list_litigators](https://user-images.githubusercontent.com/23444/49014561-740a4600-f178-11e8-81a2-3089c5dc11a8.png)

**Comment by helena-moj** [comment]
**Service:** Prisoner money intelligence
**Phase:** Beta
**Department:** HMPPS

<kbd>![filter](https://user-images.githubusercontent.com/43538843/49814008-ad3ddb00-fd60-11e8-9c4b-c60074e83ca3.png)</kbd>

**Comment by gavinwye** [comment]
This is resolved by the #2 pattern
